set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(GWTOOLCHAIN_PREFIX ${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32)
if(DEFINED ENV{GWTOOLCHAIN_THREADMODEL})
	set(GWTOOLCHAIN_THREADMODEL $ENV{GWTOOLCHAIN_THREADMODEL})
else()
	set(GWTOOLCHAIN_THREADMODEL "")
endif()

# specify the cross compiler
set(CMAKE_C_COMPILER ${GWTOOLCHAIN_PREFIX}-gcc${GWTOOLCHAIN_THREADMODEL})
set(CMAKE_CXX_COMPILER ${GWTOOLCHAIN_PREFIX}-g++${GWTOOLCHAIN_THREADMODEL})
set(CMAKE_RC_COMPILER ${GWTOOLCHAIN_PREFIX}-windres)

# where is the target environment
set(CMAKE_FIND_ROOT_PATH /usr/${GWTOOLCHAIN_PREFIX})

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
